export const GET_CONFLUENCE_SECTIONS = "GET_CONFLUENCE_SECTIONS"
export const SET_CONFLUENCE_FILTER = "SET_CONFLUENCE_FILTER"
export const CLEAR_CONFLUENCE_FILTER = "CLEAR_CONFLUENCE_FILTER"

export const SET_CONFLUENCE_OPENED_DOC = "SET_CONFLUENCE_OPENED_DOC";
export const SET_CONFLUENCE_OPENED_DOC_NAME = "SET_CONFLUENCE_OPENED_DOC_NAME";
export const SET_CONFLUENCE_OPENED_DOC_SECTION = "SET_CONFLUENCE_OPENED_DOC_SECTION";
export const SET_CONFLUENCE_OPENED_DOC_TAGS = "SET_CONFLUENCE_OPENED_DOC_TAGS";
export const SET_CONFLUENCE_OPENED_DOC_DESCRIPTION = "SET_CONFLUENCE_OPENED_DOC_DESCRIPTION";
export const CLEAR_CONFLUENCE_OPENED_DOC = "CLEAR_CONFLUENCE_OPENED_DOC";