export const SET_NEW_PROJECT_NAME = "SET_NEW_PROJECT_NAME"
export const SET_NEW_PROJECT_KEY = "SET_NEW_PROJECT_KEY"
export const SET_NEW_PROJECT_LEAD = "SET_NEW_PROJECT_LEAD"
export const SET_NEW_PROJECT = "SET_NEW_PROJECT"
export const CLEAR_NEW_PROJECT = "CLEAR_NEW_PROJECT"

export const CLEAN_NEW_PROJECT_FORM = "CLEAN_NEW_PROJECT_FORM"

export const GET_PROJECTS = "GET_PROJECTS"
export const SET_SELECTED_PROJECT = "SET_SELECTED_PROJECT"

export const SET_SUBMIT_FORM_MODE = "SET_SUBMIT_FORM_MODE"
export const CLEAR_SELECTED_PROJECT = "CLEAR_SELECTED_PROJECT"