export const GET_PROJECTS_FOR_ADMIN = "GET_PROJECTS_FOR_ADMIN"

export const SET_OPENED_PROJECT = "SET_OPENED_PROJECT"
export const CLEAR_OPENED_PROJECT = "CLEAR_OPENED_PROJECT"

export const SET_OPENED_PROJECT_NAME = "SET_OPENED_PROJECT_NAME"
export const SET_OPENED_PROJECT_KEY = "SET_OPENED_PROJECT_KEY"
export const SET_OPENED_PROJECT_LEAD = "SET_OPENED_PROJECT_LEAD"

export const GET_USERS_FOR_ADMIN = "GET_USERS_FOR_ADMIN"